Version: 0.2
Phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - export PYTHON_INTERPRETER=$(pyenv which python3)
  pre_build:
    commands:
      - pip3 install --upgrade pip
      - pip3 install requests[security]
      - pip3 install ansible
      - pip3 install boto
      - pip3 install boto3
      - yum clean all
      - yum -y install curl
      - yum -y install jq
      - ansible-galaxy collection install amazon.aws
  build:
    commands:
      - amazon.aws.ec2:
          key_name: ec2ansible.pem
          instance_type: t2.micro
          image: ami-08f63db601b82ff5f
          count: 1
          vpc_subnet_id: subnet-0b32335e5e7fae710
          assign_public_ip: yes
