- hosts: localhost
  tasks:
  - name: code build settup
    community.aws.aws_codebuild:
      name: my_project
      description: My nice little project
      service_role: "arn:aws:iam::434156974348:role/service-role/my_project-ec2-codebuild-service-role"
      source:
        # Possible values: BITBUCKET, CODECOMMIT, CODEPIPELINE, GITHUB, S3
        type: CODEPIPELINE
        buildspec: ''
      artifacts:
        namespaceType: NONE
        packaging: NONE
        type: CODEPIPELINE
        name: my_project
      environment:
        computeType: BUILD_GENERAL1_SMALL
        privilegedMode: "true"
        image: "aws/codebuild/amazonlinux2-x86_64-standard:3.0"
        type: LINUX_CONTAINER
        environmentVariables:
            - { name: 'PROFILE', value: 'staging' }
      encryption_key: "arn:aws:kms:ap-south-1:434156974348:alias/aws/s3"
      region: ap-south-1
      state: present