# Example for creating a pipeline for continuous deploy of Github code to an ECS cluster (container)
- hosts: localhost
  tasks:
  #- name: create iam role
  #  command:
  #    aws iam create-role --role-name AWSCodePipelineServiceRole-ap-south-1-new --assume-role-policy-document '{"Version":"2012-10-17","Statement":{"Effect":"Allow","Principal":{"Service":"codepipeline.amazonaws.com"},"Action":"sts:AssumeRole"}}'
  - name: code pipe line settup
    community.aws.aws_codepipeline:
      name: my_deploy_pipeline
      role_arn: arn:aws:iam::434156974348:role/service-role/AWSCodePipelineServiceRole-ap-south-1-new
      artifact_store:
        type: S3
        location: mys3codepiplinebucket
      stages:
        - name: Get_source
          actions:
            -
              name: Git_pull
              actionTypeId:
                category: Source
                owner: ThirdParty
                provider: GitHub
                version: '1'
              outputArtifacts:
                - { name: my-app-source }
              configuration:
                Owner: Santhosh
                Repo: ec2ansible
                PollForSourceChanges: 'true'
                Branch: master
                # Generate token like this:
                # https://docs.aws.amazon.com/codepipeline/latest/userguide/GitHub-rotate-personal-token-CLI.html
                # GH Link: https://github.com/settings/tokens
                OAuthToken: '728114c5c5fce6ab86e5f1fc90becabffef965eb'
              runOrder: 1
        - name: Build
          actions:
            -
              name: CodeBuild
              actionTypeId:
                category: Build
                owner: AWS
                provider: CodeBuild
                version: '1'
              inputArtifacts:
                - { name: my-app-source }
              outputArtifacts:
                - { name: my-app-build }
              configuration:
                # A project with that name needs to be setup on AWS CodeBuild already (use code_build module).
                ProjectName: my_project
              runOrder: 1
      region: ap-south-1
      state: present
